FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONASYNCIODEBUG=1 \
    POETRY_VERSION=2.1.3

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        build-essential \
        curl \
        gcc \
        libffi-dev \
        libpq-dev \
        libssl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s ${HOME}/.local/bin/poetry /usr/local/bin/poetry

WORKDIR /app

COPY ./pyproject.toml ./poetry.lock ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --no-root

EXPOSE 8080

CMD [ "poetry", "run", "python", "-m", "app" ]
